version: "3.8"

networks:
  traefik-proxy-network:
    name: proxy-net

services:
  ### Traefik
  traefik:
    labels:
      - "traefik.frontend.rule=Host:${SERVICE_NAME}.${DOMAIN}"
      - "traefik.docker.network=proxy-net"
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirects.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirects.entrypoints=http"
      - "traefik.http.routers.redirects.middlewares=redirect-to-https"
    environment:
      - APP_VER
      - CF_API_EMAIL
      - CF_DNS_API_TOKEN
      - DASHBOARD
      - DNS_CHALLENGE
      - DOCKER_TRAEFIK_VER
      - DOMAIN
      - INSECURE
      - LOG_LEVEL
      - PROVIDER
      - SERVICE_NAME
    networks:
      - "traefik-proxy-network"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./data/certs:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: "always"
    build:
      context: "./docker/traefik"
      args:
        - "DOCKER_TRAEFIK_VER=${DOCKER_TRAEFIK_VER}"
    command:
      # Should the dashboard be enabled?
      - "--api.insecure=${INSECURE}"
      - "--api.dashboard=${DASHBOARD}"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      # Enable ping
      - "--ping"
      - "--entryPoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.https.http.tls=true"
      # Enable automated DNS challenges for SSL?
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=${DNS_CHALLENGE}"
      # What provider should be used.
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=${PROVIDER}"
      # The email to provide to let's encrypt
      - "--certificatesresolvers.letsencrypt.acme.email=${CF_API_EMAIL}"
      # Certificate storage location.
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # Uncomment the following lines if you would like to debug
      #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # Enable or disable debug mode
      - "--log.level=${LOG_LEVEL}"
