version: "3"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  ### Traefik ################################
  traefik:
    build:
      context: ./docker/traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - backend
      - frontend
    labels:
      - traefik.entryPoints.web.forwardedHeaders.trustedIPs=172.18.0.0/16

  ### NGINX Server #######################################
  nginx:
    build:
      context: ./docker/nginx
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.web.priority=1"
      - "traefik.docker.network=backend"
      #- "traefik.http.routers.web.middlewares=whiteList"
      #- "traefik.http.middlewares.whiteList.ipwhitelist.sourcerange=127.0.0.1/32, 192.168.1.1/32, 172.17.0.1/32, 172.18.0.1/32"
      #- "traefik.http.middlewares.whiteList.ipwhitelist.ipstrategy.depth=2"
